### ISSUE TITLE
Help understanding functions

### ISSUE THREAD

**Issue by dustinxwhite** [ancalex/Tetrakis_Square_Tiling_with_WS2812_LEDS#1]
I'm having trouble understanding this segment of code, as the various functions (such as "one_cell_no_symmetry") are not defined within the included "functions.h"

switch (function) {
	case 0: one_cell_no_symmetry(); break;
	case 1: one_cell_horizontal_symmetry(); break;
	case 2: one_cell_vertical_symmetry(); break;
	case 3: one_cell_both_symmetry(); break;
	case 4: four_cells_no_symmetry(); break;
	case 5: four_cells_horizontal_symmetry(); break;
	case 6: four_cells_vertical_symmetry(); break;
	case 7: four_cells_both_symmetry(); break;
	case 8: sixteen_cells_both_symmetry(); break;
	}

**Comment by ancalex** [comment]
one_cell_no_symmetry
is defined from line 64 to 78 in functions.h

**Comment by dustinxwhite** [comment]
> one_cell_no_symmetry is defined from line 64 to 78 in functions.h

Thank you! I had saved functions.h in the wrong directory.
